name: PURLs Submission Action with Manifest
description: "Submit some PURLs to the Dependency Submission API"
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Actions runner."
    required: false
    default: ${{ github.token }}
  detector-name:
    description: "Name of the detector"
    required: false
    default: purls-submission-action
  snapshot1-correlator:
    description: "Correlator for snapshot 1"
    required: false
    default: purls-submission-correlator
  snapshot1-manifest-name:
    description: "The name of the manifest for snapshot 1"
    required: true
  snapshot1-manifest-path:
    description: "The filepath to the manifest file for snapshot 1"
    required: true
  snapshot1-purls:
    description: "The PURLs to submit for snapshot 1, one per line"
    required: true
  snapshot2-correlator:
    description: "Correlator for snapshot 2"
    required: false
    default: purls-submission-correlator
  snapshot2-manifest-name:
    description: "The name of the manifest for snapshot 2"
    required: false
  snapshot2-manifest-path:
    description: "The filepath to the manifest file for snapshot 2"
    required: false
  snapshot2-purls:
    description: "The PURLs to submit for snapshot 2, one per line"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
