name: PURLs Submission Action with Manifest
description: "Submit some PURLs to the Dependency Submission API"
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Actions runner."
    required: false
    default: ${{ github.token }}
  manifest-name:
    description: "The name of the manifest"
    required: true
    default: "."
  manifest-path:
    description: "The filepath to the manifest file"
    required: true
    default: "."
  purls:
    description: "The PURLs to submit, one per line"
    required: true
    default: "."
  detector-name:
    description: "Name of the detector"
    required: false
    default: purls-submission-action
  correlator-name:
    description: "Name of the correlator"
    required: false
    default: purls-submission-correlator
runs:
  using: "node16"
  main: "dist/index.js"
